{
    "data":{
        "keyword":"广州",
        "totalCount":728,
        "currentPage":1,
        "normalKeyword":"广州",
        "filter":{
            "cities":[
                {
                    "name":"广州",
                    "pinyin":"guangzhou",
                    "foreign":false
                },
                {
                    "name":"金华",
                    "pinyin":"jinhua",
                    "foreign":false
                }
            ],
            "skus":[
                {
                    "id":365,
                    "title":"开启激情逐浪之旅"
                },
                {
                    "id":114,
                    "title":"广东赏花好去处"
                },
                {
                    "id":104,
                    "title":"广州必游TOP10"
                },
                {
                    "id":103,
                    "title":"宝贝亲子游乐地"
                },
                {
                    "id":101,
                    "title":"自然户外好去处"
                },
                {
                    "id":386,
                    "title":"暑期玩转粤港澳"
                },
                {
                    "id":450,
                    "title":"欢乐长隆"
                },
                {
                    "id":348,
                    "title":"羊城民俗风情游"
                },
                {
                    "id":467,
                    "title":"广州赏秋大搜罗"
                }
            ],
            "subjects":[
                {
                    "count":80,
                    "name":"农家度假"
                },
                {
                    "count":53,
                    "name":"公园"
                },
                {
                    "count":51,
                    "name":"游乐场"
                },
                {
                    "count":48,
                    "name":"运动健身"
                },
                {
                    "count":39,
                    "name":"文化古迹"
                },
                {
                    "count":37,
                    "name":"采摘"
                },
                {
                    "count":35,
                    "name":"室内娱乐"
                },
                {
                    "count":34,
                    "name":"演出"
                },
                {
                    "count":31,
                    "name":"城市观光"
                },
                {
                    "count":31,
                    "name":"户外拓展"
                },
                {
                    "count":30,
                    "name":"其他公园"
                },
                {
                    "count":28,
                    "name":"密室逃脱"
                },
                {
                    "count":28,
                    "name":"展馆"
                },
                {
                    "count":27,
                    "name":"温泉"
                },
                {
                    "count":25,
                    "name":"儿童乐园"
                },
                {
                    "count":21,
                    "name":"生活休闲"
                },
                {
                    "count":20,
                    "name":"自然风光"
                },
                {
                    "count":19,
                    "name":"手工"
                },
                {
                    "count":16,
                    "name":"健身"
                },
                {
                    "count":16,
                    "name":"其他游乐场"
                },
                {
                    "count":16,
                    "name":"演出场馆"
                },
                {
                    "count":15,
                    "name":"DIY"
                },
                {
                    "count":15,
                    "name":"农家乐"
                },
                {
                    "count":15,
                    "name":"寺庙"
                },
                {
                    "count":14,
                    "name":"度假村"
                },
                {
                    "count":14,
                    "name":"真人CS"
                },
                {
                    "count":13,
                    "name":"体验馆"
                },
                {
                    "count":13,
                    "name":"古建筑"
                },
                {
                    "count":12,
                    "name":"体育馆"
                },
                {
                    "count":12,
                    "name":"餐饮"
                },
                {
                    "count":11,
                    "name":"展览馆"
                },
                {
                    "count":11,
                    "name":"活动"
                },
                {
                    "count":11,
                    "name":"高尔夫"
                },
                {
                    "count":10,
                    "name":"交通"
                },
                {
                    "count":10,
                    "name":"博物馆"
                },
                {
                    "count":10,
                    "name":"拓展"
                },
                {
                    "count":10,
                    "name":"森林公园"
                },
                {
                    "count":9,
                    "name":"庄园"
                },
                {
                    "count":9,
                    "name":"话剧歌剧"
                },
                {
                    "count":8,
                    "name":"广场"
                },
                {
                    "count":8,
                    "name":"水上乐园"
                },
                {
                    "count":7,
                    "name":"其他餐饮"
                },
                {
                    "count":7,
                    "name":"动物园"
                },
                {
                    "count":7,
                    "name":"水上玩乐"
                },
                {
                    "count":7,
                    "name":"海滨海岛"
                },
                {
                    "count":7,
                    "name":"游船"
                },
                {
                    "count":7,
                    "name":"漂流"
                },
                {
                    "count":7,
                    "name":"烘焙"
                },
                {
                    "count":7,
                    "name":"码头"
                },
                {
                    "count":6,
                    "name":"3D、4D、5D艺术体验馆"
                },
                {
                    "count":6,
                    "name":"SPA"
                },
                {
                    "count":6,
                    "name":"展览"
                },
                {
                    "count":6,
                    "name":"山川"
                },
                {
                    "count":6,
                    "name":"生态园"
                },
                {
                    "count":6,
                    "name":"荔枝"
                },
                {
                    "count":6,
                    "name":"购物"
                },
                {
                    "count":6,
                    "name":"陵墓陵园"
                },
                {
                    "count":5,
                    "name":"主题公园"
                },
                {
                    "count":5,
                    "name":"卡丁车"
                },
                {
                    "count":5,
                    "name":"租车"
                },
                {
                    "count":4,
                    "name":"儿童体验馆"
                },
                {
                    "count":4,
                    "name":"嘉年华"
                },
                {
                    "count":4,
                    "name":"城市标志建筑"
                },
                {
                    "count":4,
                    "name":"湿地公园"
                },
                {
                    "count":4,
                    "name":"滑冰"
                },
                {
                    "count":4,
                    "name":"瀑布"
                },
                {
                    "count":4,
                    "name":"电影"
                },
                {
                    "count":3,
                    "name":"其他动物园"
                },
                {
                    "count":3,
                    "name":"其他城市观光"
                },
                {
                    "count":3,
                    "name":"其他游船"
                },
                {
                    "count":3,
                    "name":"古镇"
                },
                {
                    "count":3,
                    "name":"园林"
                },
                {
                    "count":3,
                    "name":"峡谷"
                },
                {
                    "count":3,
                    "name":"摄影"
                },
                {
                    "count":3,
                    "name":"桌游"
                },
                {
                    "count":3,
                    "name":"植物园"
                },
                {
                    "count":3,
                    "name":"江河湖泊"
                },
                {
                    "count":3,
                    "name":"游泳"
                },
                {
                    "count":3,
                    "name":"露天"
                },
                {
                    "count":3,
                    "name":"骑马"
                },
                {
                    "count":3,
                    "name":"鱼疗"
                },
                {
                    "count":2,
                    "name":"主题乐园"
                },
                {
                    "count":2,
                    "name":"其他体验馆"
                },
                {
                    "count":2,
                    "name":"其他演出"
                },
                {
                    "count":2,
                    "name":"其他生活休闲"
                },
                {
                    "count":2,
                    "name":"其他购物"
                },
                {
                    "count":2,
                    "name":"古街"
                },
                {
                    "count":2,
                    "name":"台球"
                },
                {
                    "count":2,
                    "name":"咖啡酒吧茶馆"
                },
                {
                    "count":2,
                    "name":"商场"
                },
                {
                    "count":2,
                    "name":"大学"
                },
                {
                    "count":2,
                    "name":"宗教"
                },
                {
                    "count":2,
                    "name":"按摩"
                },
                {
                    "count":2,
                    "name":"故居"
                },
                {
                    "count":2,
                    "name":"教堂"
                },
                {
                    "count":2,
                    "name":"步行街"
                },
                {
                    "count":2,
                    "name":"海洋馆"
                },
                {
                    "count":2,
                    "name":"深层矿泉"
                },
                {
                    "count":2,
                    "name":"湿地"
                },
                {
                    "count":2,
                    "name":"瑜伽"
                },
                {
                    "count":2,
                    "name":"纪念馆"
                },
                {
                    "count":2,
                    "name":"综合动物园"
                },
                {
                    "count":2,
                    "name":"舞蹈"
                },
                {
                    "count":2,
                    "name":"葡萄"
                },
                {
                    "count":2,
                    "name":"蜡像馆"
                },
                {
                    "count":2,
                    "name":"观光巴士"
                },
                {
                    "count":2,
                    "name":"足疗"
                },
                {
                    "count":2,
                    "name":"道教"
                },
                {
                    "count":2,
                    "name":"遗址"
                },
                {
                    "count":2,
                    "name":"陶艺"
                },
                {
                    "count":1,
                    "name":"世界遗产"
                },
                {
                    "count":1,
                    "name":"东南亚餐"
                },
                {
                    "count":1,
                    "name":"中式园林"
                },
                {
                    "count":1,
                    "name":"人文艺术馆"
                },
                {
                    "count":1,
                    "name":"儿童公园"
                },
                {
                    "count":1,
                    "name":"儿童剧"
                },
                {
                    "count":1,
                    "name":"其他交通"
                },
                {
                    "count":1,
                    "name":"其他室内娱乐"
                },
                {
                    "count":1,
                    "name":"冰雪嘉年华"
                },
                {
                    "count":1,
                    "name":"博览园"
                },
                {
                    "count":1,
                    "name":"地质公园"
                },
                {
                    "count":1,
                    "name":"地质景观"
                },
                {
                    "count":1,
                    "name":"城际巴士"
                },
                {
                    "count":1,
                    "name":"婴儿游泳馆"
                },
                {
                    "count":1,
                    "name":"影视基地"
                },
                {
                    "count":1,
                    "name":"摩天轮"
                },
                {
                    "count":1,
                    "name":"景酒套餐"
                },
                {
                    "count":1,
                    "name":"智选假日"
                },
                {
                    "count":1,
                    "name":"森林"
                },
                {
                    "count":1,
                    "name":"水乡"
                },
                {
                    "count":1,
                    "name":"洗浴中心"
                },
                {
                    "count":1,
                    "name":"海鲜"
                },
                {
                    "count":1,
                    "name":"滑雪"
                },
                {
                    "count":1,
                    "name":"特产"
                },
                {
                    "count":1,
                    "name":"电玩店"
                },
                {
                    "count":1,
                    "name":"直通车"
                },
                {
                    "count":1,
                    "name":"科技馆"
                },
                {
                    "count":1,
                    "name":"空中飞行体验"
                },
                {
                    "count":1,
                    "name":"竹海"
                },
                {
                    "count":1,
                    "name":"纪念碑"
                },
                {
                    "count":1,
                    "name":"美容美体"
                },
                {
                    "count":1,
                    "name":"美术馆"
                },
                {
                    "count":1,
                    "name":"羽毛球"
                },
                {
                    "count":1,
                    "name":"自助餐"
                },
                {
                    "count":1,
                    "name":"萤火虫"
                },
                {
                    "count":1,
                    "name":"观景台"
                },
                {
                    "count":1,
                    "name":"钓鱼"
                },
                {
                    "count":1,
                    "name":"雕像"
                },
                {
                    "count":1,
                    "name":"雕塑喷泉"
                },
                {
                    "count":1,
                    "name":"音乐会"
                },
                {
                    "count":1,
                    "name":"音乐节"
                },
                {
                    "count":1,
                    "name":"鳄鱼"
                }
            ],
            "groupCities":[
                
            ]
        },
        "sightList":[
            {
                "star":"5A",
                "score":"3.5",
                "tuan":false,
                "sightId":371131297,
                "intro":"爸爸去哪儿？去长隆旅游度假区啊",
                "free":false,
                "point":"113.34079,23.011494",
                "address":"广东省广州市番禺区番禺大道",
                "foreign":false,
                "sightName":"广州长隆旅游度假区",
                "districts":"广东·广州·番禺",
                "childrenCount":6,
                "sightCategory":"普通",
                "childrenList":[
                    {
                        "id":38131,
                        "parentId":0,
                        "name":"长隆国际大马戏剧院",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":13425,
                        "parentId":0,
                        "name":"广州鳄鱼公园",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":32468,
                        "parentId":0,
                        "name":"长隆欢乐世界",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":13212,
                        "parentId":0,
                        "name":"长隆水上乐园",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":186982,
                        "parentId":0,
                        "name":"广州长隆酒店白虎餐厅",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":14709,
                        "parentId":0,
                        "name":"长隆野生动物世界",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    }
                ],
                "saleCount":5857,
                "qunarPrice":"43",
                "marketPrice":"45",
                "discount":"9.5",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/3b/3bd311262ee06d8c90.img.jpg_280x200_f80a4907.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDEzNjI4JTI2dHlwZSUzRDAlMjZpZHglM0QxJTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "star":"5A",
                "score":"3.7",
                "tuan":false,
                "sightId":4281924223,
                "intro":"爸爸去哪儿大电影拍摄地",
                "free":false,
                "point":"113.330685,23.008276",
                "address":"广东省广州市番禺区迎宾路长隆旅游度假村旁",
                "foreign":false,
                "sightName":"长隆野生动物世界",
                "districts":"广东·广州·广州长隆旅游度假区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":3327,
                "qunarPrice":"99",
                "marketPrice":"100",
                "discount":"9.9",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1507/92/fa6cf0a5deba2ecedc2ccfaa4905140b.water.jpg_280x200_2c7cf67c.jpg",
                "parentSightId":13628,
                "parentSightName":"广州长隆旅游度假区",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDE0NzA5JTI2dHlwZSUzRDAlMjZpZHglM0QyJTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "score":"0.0",
                "tuan":false,
                "sightId":3397249921,
                "intro":"汇粹全球马戏精华，打造世界马戏之最",
                "free":false,
                "point":"113.339108,23.00889",
                "address":"广东省广州市番禺区迎宾路长隆欢乐世界东门侧",
                "foreign":false,
                "sightName":"长隆国际大马戏剧院",
                "districts":"广东·广州·广州长隆旅游度假区",
                "childrenCount":0,
                "sightCategory":"表演",
                "saleCount":2142,
                "qunarPrice":"188",
                "marketPrice":"380",
                "discount":"4.9",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1507/9e/7b5e0a44cb0310280b1aeb2a8dd94de8.water.jpg_280x200_6af68289.jpg",
                "parentSightId":13628,
                "parentSightName":"广州长隆旅游度假区",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDM4MTMxJTI2dHlwZSUzRDAlMjZpZHglM0QzJTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "star":"5A",
                "score":"0.0",
                "tuan":false,
                "sightId":2637958213,
                "intro":"爸爸去哪儿？去广州长隆欢乐世界吧",
                "free":false,
                "point":"113.33789,23.005235",
                "address":"广东省广州市番禺区长隆旅游度假区内",
                "foreign":false,
                "sightName":"长隆欢乐世界",
                "districts":"广东·广州·广州长隆旅游度假区",
                "childrenCount":3,
                "sightCategory":"普通",
                "childrenList":[
                    {
                        "id":16858,
                        "parentId":0,
                        "name":"哈比王国",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":18731,
                        "parentId":0,
                        "name":"旋风岛",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":18446,
                        "parentId":0,
                        "name":"尖叫地带",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    }
                ],
                "saleCount":1810,
                "qunarPrice":"90",
                "marketPrice":"120",
                "discount":"7.5",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1510/5b/5bc14b93bd2386c2.img.jpg_280x200_bedea05e.jpg",
                "parentSightId":13628,
                "parentSightName":"广州长隆旅游度假区",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDMyNDY4JTI2dHlwZSUzRDAlMjZpZHglM0Q0JTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "star":"5A",
                "score":"3.6",
                "tuan":false,
                "sightId":3604690050,
                "intro":"世界水上游乐项目最多的大型水上乐园",
                "free":false,
                "point":"113.330659,23.008301",
                "address":"广东省广州市番禺区迎宾路长隆旅游度假区内",
                "foreign":false,
                "sightName":"长隆水上乐园",
                "districts":"广东·广州·广州长隆旅游度假区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":612,
                "qunarPrice":"88",
                "marketPrice":"200",
                "discount":"4.4",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/1a/1a21361dd2b4691c90.img.jpg_280x200_b3862ae7.jpg",
                "parentSightId":13628,
                "parentSightName":"广州长隆旅游度假区",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDEzMjEyJTI2dHlwZSUzRDAlMjZpZHglM0Q1JTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "score":"0.0",
                "tuan":false,
                "sightId":303066616,
                "intro":"华灯初上，江中体验城市的霓虹与繁华",
                "free":false,
                "point":"113.277534,23.121129",
                "address":"广东省广州市越秀区",
                "foreign":false,
                "sightName":"珠江夜游",
                "districts":"广东·广州",
                "childrenCount":7,
                "sightCategory":"交通",
                "childrenList":[
                    {
                        "id":194225,
                        "parentId":0,
                        "name":"珠江夜游广州塔码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":38556,
                        "parentId":0,
                        "name":"珠江夜游大沙头码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":187117,
                        "parentId":0,
                        "name":"珠江夜游芳村码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":187120,
                        "parentId":0,
                        "name":"珠江夜游省总码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":37605,
                        "parentId":0,
                        "name":"珠江夜游天字码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":187118,
                        "parentId":0,
                        "name":"珠江夜游中大码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":187119,
                        "parentId":0,
                        "name":"珠江夜游西提码头",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    }
                ],
                "saleCount":826,
                "qunarPrice":"36",
                "marketPrice":"58",
                "discount":"6.2",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/1c/1c67791edbe2677b90.img.jpg_280x200_89feb6ec.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDE5NzE5MCUyNnR5cGUlM0QwJTI2aWR4JTNENiUyNnF0JTNEcmVnaW9uJTI2YXBrJTNEbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnNjJTNEV1dXJTI2YWJ0cmFjZSUzRGt3JTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0bHIlNDAlRTUlQjklQkYlRTUlQjclOUUlMjRiZW5XYWlEaSU0MCVFNiU5QyVBQyVFNSU5QyVCMCUyNHVyJTQwJTI0cXQlNDByZWdpb24lMjRhcHBLZXklNDBtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2dXIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZsciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmZ0JTNEJTdCJTdE"
            },
            {
                "star":"4A",
                "score":"0.0",
                "tuan":false,
                "sightId":3941562390,
                "intro":"360度羊城全貌，感受王者之居高临下",
                "free":false,
                "point":"113.330995,23.112229",
                "address":"广东省广州市海珠区阅江西路222号",
                "foreign":false,
                "sightName":"广州塔",
                "districts":"广东·广州·海珠区",
                "childrenCount":6,
                "sightCategory":"普通",
                "childrenList":[
                    {
                        "id":195904,
                        "parentId":0,
                        "name":"广州塔童梦奇园",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":191802,
                        "parentId":0,
                        "name":"488Deck云霄平台",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":187680,
                        "parentId":0,
                        "name":"广州塔摩天轮",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":191803,
                        "parentId":0,
                        "name":"广州塔速降体验",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":195259,
                        "parentId":0,
                        "name":"璇玑地中海自助旋转餐厅",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":196754,
                        "parentId":0,
                        "name":"蜘蛛侠栈道",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    }
                ],
                "saleCount":478,
                "qunarPrice":"71",
                "marketPrice":"75",
                "discount":"9.4",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/ee/ee2fb567add7969390.water.jpg_280x200_7fcdc0af.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDMzNjMxJTI2dHlwZSUzRDAlMjZpZHglM0Q3JTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "score":"3.6",
                "tuan":false,
                "sightId":3801843901,
                "intro":"来世界最大的鳄鱼公园探索鳄鱼世界",
                "free":false,
                "point":"113.282779,23.032299",
                "address":"广东省广州市番禺市大石镇大边村石北大道",
                "foreign":false,
                "sightName":"广州鳄鱼公园",
                "districts":"广东·广州·广州长隆旅游度假区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":448,
                "qunarPrice":"43",
                "marketPrice":"45",
                "discount":"9.5",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1508/df/80d9451355fcc7cdf406dca8ae89f583.water.jpg_280x200_ca8eabe5.jpg",
                "parentSightId":13628,
                "parentSightName":"广州长隆旅游度假区",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDEzNDI1JTI2dHlwZSUzRDAlMjZpZHglM0Q4JTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "star":"4A",
                "score":"3.7",
                "tuan":false,
                "sightId":3633837019,
                "intro":"岭南景致，千种印象",
                "free":false,
                "point":"113.411898,23.041453",
                "address":"广东省广州市番禺区外环西路",
                "foreign":false,
                "sightName":"岭南印象园",
                "districts":"广东·广州·番禺",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":344,
                "qunarPrice":"30",
                "marketPrice":"30",
                "discount":"10",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1604/17/17df2648c02cb5ec90.img.jpg_280x200_f248c268.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDMwMCUyNnR5cGUlM0QwJTI2aWR4JTNEOSUyNnF0JTNEcmVnaW9uJTI2YXBrJTNEbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnNjJTNEV1dXJTI2YWJ0cmFjZSUzRGt3JTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0bHIlNDAlRTUlQjklQkYlRTUlQjclOUUlMjRiZW5XYWlEaSU0MCVFNiU5QyVBQyVFNSU5QyVCMCUyNHVyJTQwJTI0cXQlNDByZWdpb24lMjRhcHBLZXklNDBtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2dXIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZsciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmZ0JTNEJTdCJTdE"
            },
            {
                "score":"3.5",
                "tuan":false,
                "sightId":3258940834,
                "intro":"华南区最大的香草主题公园",
                "free":false,
                "point":"113.267397,23.46772",
                "address":"广东省广州市花都区花山镇铁山村香草世界",
                "foreign":false,
                "sightName":"香草世界",
                "districts":"广东·广州·花都",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":78,
                "qunarPrice":"45",
                "marketPrice":"60",
                "discount":"7.5",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1505/90/90d5fe352345df2e.water.jpg_280x200_8be8fc01.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDU4MzglMjZ0eXBlJTNEMCUyNmlkeCUzRDEwJTI2cXQlM0RyZWdpb24lMjZhcGslM0RtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2c2MlM0RXV1clMjZhYnRyYWNlJTNEa3clNDAlRTUlQjklQkYlRTUlQjclOUUlMjRsciU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGJlbldhaURpJTQwJUU2JTlDJUFDJUU1JTlDJUIwJTI0dXIlNDAlMjRxdCU0MHJlZ2lvbiUyNGFwcEtleSU0MG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZ1ciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmxyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2ZnQlM0QlN0IlN0Q%3D"
            },
            {
                "score":"0.0",
                "tuan":false,
                "sightId":1523309447,
                "intro":"全球最高横向摩天轮",
                "free":false,
                "point":"113.330433,23.111711",
                "address":"广东省广州市海珠区阅江西路222号广州塔塔顶平台",
                "foreign":false,
                "sightName":"广州塔摩天轮",
                "districts":"广东·广州·广州塔",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":140,
                "qunarPrice":"263",
                "marketPrice":"298",
                "discount":"8.8",
                "sightImgURL":"http://img1.qunarzz.com/travel/poi/1506/6e/7aba211ccbe294.jpg_280x200_b1175c26.jpg",
                "parentSightId":33631,
                "parentSightName":"广州塔",
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDE4NzY4MCUyNnR5cGUlM0QwJTI2aWR4JTNEMTElMjZxdCUzRHJlZ2lvbiUyNmFwayUzRG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZzYyUzRFdXVyUyNmFidHJhY2UlM0RrdyU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGxyJTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0YmVuV2FpRGklNDAlRTYlOUMlQUMlRTUlOUMlQjAlMjR1ciU0MCUyNHF0JTQwcmVnaW9uJTI0YXBwS2V5JTQwbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnVyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2bHIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZmdCUzRCU3QiU3RA%3D%3D"
            },
            {
                "score":"3.6",
                "tuan":false,
                "sightId":1604631181,
                "intro":"彩虹乐园---百万葵园巨资唯美奉献",
                "free":false,
                "point":"113.62679,22.634301",
                "address":"广东省广州市南沙区万顷沙镇新垦15涌（原百万葵园）",
                "foreign":false,
                "sightName":"南沙百万葵园",
                "districts":"广东·广州·南沙区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":84,
                "qunarPrice":"43",
                "marketPrice":"48",
                "discount":"8.9",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/3c/3c514c20a740128b90.water.jpg_280x200_2137e3ba.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDYxOSUyNnR5cGUlM0QwJTI2aWR4JTNEMTIlMjZxdCUzRHJlZ2lvbiUyNmFwayUzRG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZzYyUzRFdXVyUyNmFidHJhY2UlM0RrdyU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGxyJTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0YmVuV2FpRGklNDAlRTYlOUMlQUMlRTUlOUMlQjAlMjR1ciU0MCUyNHF0JTQwcmVnaW9uJTI0YXBwS2V5JTQwbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnVyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2bHIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZmdCUzRCU3QiU3RA%3D%3D"
            },
            {
                "star":"4A",
                "score":"3.6",
                "tuan":false,
                "sightId":3312871028,
                "intro":"历史最久种类最多面积最大的南亚热带植物园",
                "free":false,
                "point":"113.373013,23.18862",
                "address":"广东省广州市天河区天源路1190号",
                "foreign":false,
                "sightName":"华南植物园",
                "districts":"广东·广州·天河区",
                "childrenCount":2,
                "sightCategory":"普通",
                "childrenList":[
                    {
                        "id":24494,
                        "parentId":0,
                        "name":"孢子与阴生植物园",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    },
                    {
                        "id":191273,
                        "parentId":0,
                        "name":"华南植物园温室群",
                        "saleCount":0,
                        "recommend":0,
                        "recommendLevel":0.0,
                        "userId":0
                    }
                ],
                "saleCount":666,
                "qunarPrice":"9.1",
                "marketPrice":"20",
                "discount":"4.5",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1603/db/dbf7515e2177ef4a90.water.jpg_280x200_a136cb36.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDE0NzUzJTI2dHlwZSUzRDAlMjZpZHglM0QxMyUyNnF0JTNEcmVnaW9uJTI2YXBrJTNEbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnNjJTNEV1dXJTI2YWJ0cmFjZSUzRGt3JTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0bHIlNDAlRTUlQjklQkYlRTUlQjclOUUlMjRiZW5XYWlEaSU0MCVFNiU5QyVBQyVFNSU5QyVCMCUyNHVyJTQwJTI0cXQlNDByZWdpb24lMjRhcHBLZXklNDBtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2dXIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZsciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmZ0JTNEJTdCJTdE"
            },
            {
                "score":"0.0",
                "tuan":false,
                "sightId":1766306611,
                "intro":"集3D画展.5D错觉.4D滑稽世界等游戏",
                "free":false,
                "point":"113.323681,23.146261",
                "address":"广东省广州市天河区天河北路28号时代广场4楼",
                "foreign":false,
                "sightName":"广州星空错觉艺术馆",
                "districts":"广东·广州·天河区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":42,
                "qunarPrice":"48",
                "marketPrice":"80",
                "discount":"6",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/1506/15/152407f355752db4.water.jpg_280x200_24051e05.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDQ1MDgzOSUyNnR5cGUlM0QwJTI2aWR4JTNEMTQlMjZxdCUzRHJlZ2lvbiUyNmFwayUzRG1wX3BpYW9fd3d3X2xpc3RfaW5wdXRTZWFyY2glMjZzYyUzRFdXVyUyNmFidHJhY2UlM0RrdyU0MCVFNSVCOSVCRiVFNSVCNyU5RSUyNGxyJTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0YmVuV2FpRGklNDAlRTYlOUMlQUMlRTUlOUMlQjAlMjR1ciU0MCUyNHF0JTQwcmVnaW9uJTI0YXBwS2V5JTQwbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnVyJTNEJUU1JUI5JUJGJUU1JUI3JTlFJTI2bHIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZmdCUzRCU3QiU3RA%3D%3D"
            },
            {
                "score":"0.0",
                "tuan":false,
                "sightId":3395585126,
                "intro":"让孩子感知成人的苦与乐、忙碌与责任",
                "free":false,
                "point":"113.270365,23.186314",
                "address":"广州市白云区云霄路353栋5号停机坪购物广场2楼（离万达广场约10分钟路程）",
                "foreign":false,
                "sightName":"广州星期8小镇",
                "districts":"广东·广州·白云区",
                "childrenCount":0,
                "sightCategory":"普通",
                "saleCount":36,
                "qunarPrice":"29",
                "marketPrice":"50",
                "discount":"5.8",
                "sightImgURL":"http://img1.qunarzz.com/sight/p0/201403/10/304b115ac96857308547caf29b96158c.jpg_280x200_d8d11b2b.jpg",
                "parentSightId":0,
                "hasPromotion":false,
                "recommend":false,
                "recommendLevel":"0.0",
                "searchTrace":"a3clM0QlRTUlQjklQkYlRTUlQjclOUUlMjZpZCUzRDM4NTI0JTI2dHlwZSUzRDAlMjZpZHglM0QxNSUyNnF0JTNEcmVnaW9uJTI2YXBrJTNEbXBfcGlhb193d3dfbGlzdF9pbnB1dFNlYXJjaCUyNnNjJTNEV1dXJTI2YWJ0cmFjZSUzRGt3JTQwJUU1JUI5JUJGJUU1JUI3JTlFJTI0bHIlNDAlRTUlQjklQkYlRTUlQjclOUUlMjRiZW5XYWlEaSU0MCVFNiU5QyVBQyVFNSU5QyVCMCUyNHVyJTQwJTI0cXQlNDByZWdpb24lMjRhcHBLZXklNDBtcF9waWFvX3d3d19saXN0X2lucHV0U2VhcmNoJTI2dXIlM0QlRTUlQjklQkYlRTUlQjclOUUlMjZsciUzRCVFNSVCOSVCRiVFNSVCNyU5RSUyNmZ0JTNEJTdCJTdE"
            }
        ]
    },
    "ret":true
}